# Generated by Django 6.0.3 on 2026-04-30 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones_nombre__estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='identificacion',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='La identificación debe contener entre 5 y 15 dígitos numéricos.', regex='^\\d{5,15}$')]),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='nota1',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='nota2',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='nota3',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
